language: ruby
rvm:
  - 2.1.6
before_script:
  - "bundle exec rake db:setup"
script: "bundle exec rake --trace"
deploy:
  provider: heroku
  api_key:
    secure: "B6AgzJFIRytdDGvVGHXx6O+GOStyNMdMLxnlrBjVBuoQLQAvG//+w8INJtmjsaMLsTPT2oDaiNkmyCZhOlFO2yOHyk8v6NKd3ejs7rMouwvhgGEbBEYdNVkLu6ghg6rn2fTGbUpKN9m0HW0uvkBZEXO43uUvwdhz+SSHYhM6fto="
  app: "demo-captains-log"
  run: "rake db:setup"
